services:
  - type: web
    name: invoiceflow
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn django_proj.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0