# Generated by Django 5.2.11 on 2026-02-25 18:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger', models.CharField(choices=[('before_due', 'Before Due Date'), ('on_due', 'On Due Date'), ('after_due', 'After Due Date (Overdue)')], max_length=20)),
                ('days_offset', models.IntegerField(default=0, help_text='Number of days before/after due date to send reminder')),
                ('is_active', models.BooleanField(default=True)),
                ('subject_template', models.CharField(default='Payment reminder for invoice {invoice_number}', max_length=200)),
                ('body_template', models.TextField(default='Dear {client_name},\n\nThis is a reminder that invoice {invoice_number} for {amount} is due on {due_date}.\n\nThank you.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_rules', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Reminder Rule',
                'ordering': ['trigger', 'days_offset'],
            },
        ),
    ]
