# Generated by Django 5.2.11 on 2026-02-25 18:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], default='monthly', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('max_occurrences', models.IntegerField(blank=True, null=True)),
                ('occurrences_sent', models.IntegerField(default=0)),
                ('next_run_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_invoices', to='organizations.organization')),
                ('template_invoice', models.ForeignKey(help_text='Draft invoice used as template', on_delete=django.db.models.deletion.CASCADE, related_name='recurring_schedules', to='invoices.invoice')),
            ],
            options={
                'verbose_name': 'Recurring Invoice',
                'ordering': ['next_run_date'],
            },
        ),
    ]
